/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { LiveStreamEventService } from "../liveStreamEvent.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LiveStreamEventCreateInput } from "./LiveStreamEventCreateInput";
import { LiveStreamEvent } from "./LiveStreamEvent";
import { LiveStreamEventFindManyArgs } from "./LiveStreamEventFindManyArgs";
import { LiveStreamEventWhereUniqueInput } from "./LiveStreamEventWhereUniqueInput";
import { LiveStreamEventUpdateInput } from "./LiveStreamEventUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class LiveStreamEventControllerBase {
  constructor(
    protected readonly service: LiveStreamEventService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: LiveStreamEvent })
  @nestAccessControl.UseRoles({
    resource: "LiveStreamEvent",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createLiveStreamEvent(
    @common.Body() data: LiveStreamEventCreateInput
  ): Promise<LiveStreamEvent> {
    return await this.service.createLiveStreamEvent({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [LiveStreamEvent] })
  @ApiNestedQuery(LiveStreamEventFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "LiveStreamEvent",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async liveStreamEvents(
    @common.Req() request: Request
  ): Promise<LiveStreamEvent[]> {
    const args = plainToClass(LiveStreamEventFindManyArgs, request.query);
    return this.service.liveStreamEvents({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: LiveStreamEvent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LiveStreamEvent",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async liveStreamEvent(
    @common.Param() params: LiveStreamEventWhereUniqueInput
  ): Promise<LiveStreamEvent | null> {
    const result = await this.service.liveStreamEvent({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: LiveStreamEvent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LiveStreamEvent",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateLiveStreamEvent(
    @common.Param() params: LiveStreamEventWhereUniqueInput,
    @common.Body() data: LiveStreamEventUpdateInput
  ): Promise<LiveStreamEvent | null> {
    try {
      return await this.service.updateLiveStreamEvent({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: LiveStreamEvent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LiveStreamEvent",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteLiveStreamEvent(
    @common.Param() params: LiveStreamEventWhereUniqueInput
  ): Promise<LiveStreamEvent | null> {
    try {
      return await this.service.deleteLiveStreamEvent({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
